# Configs of data source
ds:
  driver: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/dailyplanner_db"
  username: "dp_user"
  password: "dp_pass"
hibernate:
  dialect: "org.hibernate.dialect.PostgreSQL95Dialect"
  show_sql: "true"
#  hikari:
#    maximum_pool_size: 5
#    pool_name: "MyHikariCP"

security:
  jwt:
    token:
      secret: "s3cr3t"
      expire: 30000000